require("custom.essential")

require("plugins.lualine")
require("plugins.theme")
require("plugins.session-manager")
require("plugins.file-manager")
require("plugins.highlight")
require("plugins.lsp")
require("plugins.completion")
require("plugins.diff")
require("plugins.snacks")
require("plugins.editing-support")
require("plugins.conform")
