k9s:
  liveViewAutoRefresh: true
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    # NOTE somehow after setting this to true, I cannot use cursor in k9s, not sure if this is a bug
    enableMouse: false
    headless: true
    logoless: true
    crumbsless: false
    reactive: true
    noIcons: false
    # TODO figure out a good skin later
    # skin: in_the_navy
  skipLatestRevCheck: true
  disablePodCounting: false
  imageScans:
    enable: false
  logger:
    tail: 100
    buffer: 1000
    sinceSeconds: -1
    textWrap: true
    showTime: false
