k9s:
  liveViewAutoRefresh: true
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: true
    headless: true
    logoless: true
    crumbsless: false
    # Toggles reactive UI. This option provide for watching on disk artifacts changes and update the UI live  Defaults to false.
    reactive: false
    # Toggles icons display as not all terminal support these chars.
    noIcons: false
    # TODO figure out a good skin later
    # skin: in_the_navy
  skipLatestRevCheck: true
  disablePodCounting: false
  imageScans:
    enable: false
  logger:
    tail: 100
    buffer: 1000
    sinceSeconds: -1
    textWrap: true
    showTime: false
