# Wait for transiant prompt in Zsh
# REF https://github.com/starship/starship/issues/888#issuecomment-580127661
format = """
$sudo\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$fill\
$status\
$cmd_duration\
$package\
$kubernetes\
$line_break\
$container\
$python\
$character"""

continuation_prompt = '[> ](dimmed white)'

[directory]
style = "blue"
truncate_to_repo = false

[character]
success_symbol = "[󰘧](purple)"
error_symbol = "[󰘧](red)"
vimcmd_symbol = "[󰘧](dimmed green)"

[git_branch]
format = "[$branch]($style)"
style = "dimmed white"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = ""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "dimmed white"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[status]
format = '[$status]($style) '
disabled = false

[fill]
symbol = ' '

[git_metrics]
disabled = true

[kubernetes]
style = "cyan"
format = '[$symbol$context( \($namespace\))]($style)'
disabled = false

[container]
style = "cyan"
format = '[$symbol \[$name\]]($style) '

[python]
format = "[$virtualenv]($style) "
style = "dimmed white"

[username]
format = '[$user]($style)'
disabled = false
aliases = {}

[hostname]
format = '@[$hostname]($style) '
disabled = false

[package]
disabled = false
display_private = true
format = '[$symbol$version]($style) '

[sudo]
format = '[\[sudo\]]($style) '
style = "bold red"
disabled = false
